
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20230607.0.5"
  config.vm.define "msamhaouS" do | control |
    control.vm.hostname = "msamhaouS"
    control.vm.network :private_network, ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "msamhaouS"
    end

    control.vm.provision "shell", path: "script.sh"

    control.vm.provision "file",
      source: "config.yaml",
      destination: "/etc/rancher/k3s/config.yaml"
    
      control.vm.provision "file",
      source: "deployment.yaml",
      destination: "deployment.yaml"

    control.vm.provision :shell , inline: <<-SHELL
      sudo systemctl restart k3s.service
    SHELL
  
  end
end
