
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.define "msamhaouS" do | control |
    control.vm.hostname = "msamhaouS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "msamhaouS"
    end

    control.vm.provision "file",
      source: "config.yaml",
      destination: "/home/vagrant/config.yaml"
    control.vm.provision "file",
      source: "kubectl_manif",
      destination: "kubectl_manif"
    control.vm.provision "shell", inline: <<-SHELL
      sudo mkdir -p /etc/rancher/k3s
      sudo mv /home/vagrant/config.yaml /etc/rancher/k3s/config.yaml
    SHELL
  
    control.vm.provision "shell", path: "script.sh"

  end
end
