Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20230607.0.5"
  config.vm.define "msamhaouS" do | control |
    control.vm.hostname = "msamhaouS"
    control.vm.network :private_network, ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "msamhaouS"
    end
    control.vm.provision :shell, inline: <<-SHELL
      sudo apt-get install ufw -y
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x kubectl
      sudo mv kubectl /usr/bin/
      echo "alias k=kubectl" >> /home/vagrant/.bashrc
      source /home/vagrant/.bashrc
      sudo ufw allow 6443/tcp
      # sudo ufw allow from 192.168.56.0/21 to any
      sudo mkdir -p /etc/rancher/k3s/
      sudo chmod 777 /etc/rancher/k3s/
    SHELL

    control.vm.provision "file",
     source: "./config.yaml",
     destination: "/etc/rancher/k3s/config.yaml"

    control.vm.provision :shell, inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --config /etc/rancher/k3s/config.yaml" sh -s - 
    SHELL
  end
 

   config.vm.define "msamhaouSW" do | control |
     control.vm.hostname = "msamhaouSW"
    control.vm.network :private_network, ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "msamhaouSW"
    end
    control.vm.provision :shell, inline: <<-SHELL
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x kubectl
      sudo mv kubectl /usr/bin/
      sudo ufw allow 6443/tcp
      echo "alias k=kubectl" >> /home/vagrant/.bashrc
      sudo mkdir -p /etc/rancher/k3s/
      sudo chmod 777 /etc/rancher/k3s/
    SHELL

    control.vm.provision "file",
      source: "./agent.config.yaml",
      destination: "/etc/rancher/k3s/config.yaml"

    control.vm.provision :shell, inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --config /etc/rancher/k3s/config.yaml" sh -s - --server https://192.168.56.110:6443
    SHELL
  end
 end
