Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.define "msamhaouS" do | control |
    control.vm.hostname = "msamhaouS"
    control.vm.network :private_network, ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "msamhaouS"
    end
    control.vm.provision :shell, inline: <<-SHELL
      sudo mkdir -p /etc/rancher/k3s/
      sudo chmod 777 /etc/rancher/k3s/
    SHELL

    control.vm.provision "file",
     source: "./config.yaml",
     destination: "/etc/rancher/k3s/config.yaml"

    control.vm.provision :shell, inline: <<-SHELL
      sudo apt-get update -y && sudo apt-get install -y curl
      curl -sfL https://get.k3s.io | sh -s - 
      until kubectl get node master &>/dev/null; do
        echo "Waiting for node master to be ready..."
        sleep 5
      done

    SHELL
  end
 

   config.vm.define "msamhaouSW" do | control |
     control.vm.hostname = "msamhaouSW"
    control.vm.network :private_network, ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "msamhaouSW"
    end
    control.vm.provision :shell, inline: <<-SHELL
      sudo mkdir -p /etc/rancher/k3s/
      sudo chmod 777 /etc/rancher/k3s/
    SHELL

    control.vm.provision "file",
      source: "./agent.config.yaml",
      destination: "/etc/rancher/k3s/config.yaml"

    control.vm.provision :shell, inline: <<-SHELL
      sudo apt-get update -y && sudo apt-get install -y curl
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --config /etc/rancher/k3s/config.yaml" sh -s - --server https://192.168.56.110:6443
    SHELL
  end
 end
