Vagrant.configure("2") do |config|
  # Debian 13 (Trixie) 64-bit box
  config.vm.box = "debian/bookworm64"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2096"
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "setup.sh", privileged: false
end
